import { Colors, F } from "../theme";

export function createStyles(C: Colors, isWide: boolean) {
  const cardBorder = { backgroundColor: C.bgCard, borderRadius: 4, borderWidth: 1, borderColor: C.border };
  const compactCardBorder = { ...cardBorder, borderRadius: 3 };
  const centerBorder = { alignItems: "center", justifyContent: "center", borderRadius: 3, borderWidth: 1 } as const;
  const actionBorder = {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 3,
    paddingVertical: 10,
  } as const;
  return {
    root: { flex: 1, flexDirection: isWide ? "row" : "column", backgroundColor: C.bg },
    sidebar: {
      width: 168,
      backgroundColor: C.bgSurface,
      borderRightWidth: 1,
      borderRightColor: C.border,
      paddingTop: 24,
      paddingBottom: 16,
      paddingHorizontal: 10,
      gap: 2,
    },
    sidebarTitle: {
      color: C.textMuted,
      fontSize: 8,
      fontWeight: "700",
      letterSpacing: 3,
      fontFamily: F.mono,
      paddingHorizontal: 8,
      paddingBottom: 14,
    },
    sidebarItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 10,
      paddingVertical: 10,
      borderRadius: 4,
    },
    sidebarItemActive: { backgroundColor: C.bgCard },
    sidebarLabel: { color: C.textSecondary, fontSize: 12, fontFamily: F.mono, letterSpacing: 0.3 },
    sidebarLabelActive: { color: C.textPrimary },
    tabBar: { flexGrow: 0, backgroundColor: C.bgSurface, borderBottomWidth: 1, borderBottomColor: C.border },
    tabBarContent: { flexGrow: 1, paddingHorizontal: 0 },
    tab: {
      flexDirection: "column",
      alignItems: "center",
      flex: 1,
      minWidth: 68,
      gap: 2,
      paddingHorizontal: 4,
      paddingVertical: 8,
      borderBottomWidth: 2,
      borderBottomColor: "transparent",
    },
    tabActive: { borderBottomColor: C.active },
    tabLabel: { color: C.textSecondary, fontSize: 8, fontWeight: "700", letterSpacing: 1, fontFamily: F.mono },
    tabLabelActive: { color: C.textPrimary },
    content: { flex: 1 },
    contentPad: { flexGrow: 1 },
    contentInner: { padding: isWide ? 24 : 16, gap: 24, width: "100%", maxWidth: isWide ? 900 : undefined },
    group: { gap: 10 },
    groupLabel: { color: C.textDim, fontSize: 9, fontWeight: "700", letterSpacing: 2.5, fontFamily: F.mono },
    groupDesc: { color: C.textSecondary, fontSize: 11, fontFamily: F.mono, letterSpacing: 0.2, marginTop: -4 },
    fieldHint: { color: C.textSecondary, fontSize: 11, fontFamily: F.mono, letterSpacing: 0.2 },
    warning: { color: C.paused, fontSize: 11, fontFamily: F.mono },
    segmentRow: { flexDirection: "row", gap: 6 },
    segment: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 11,
      paddingHorizontal: 4,
      ...cardBorder,
      gap: 3,
    },
    segmentActive: { borderColor: C.active + "70", backgroundColor: C.bgCardPinned },
    segmentLabel: { color: C.textSecondary, fontSize: 13, fontWeight: "700", fontFamily: F.mono },
    segmentLabelActive: { color: C.active },
    segmentDesc: { color: C.textMuted, fontSize: 9, fontFamily: F.mono },
    segmentDescActive: { color: C.active + "aa" },
    optionRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
      padding: 14,
      ...cardBorder,
    },
    optionRowActive: { borderColor: C.active + "60", backgroundColor: C.bgCardPinned },
    radio: { width: 16, height: 16, borderRadius: 8, borderWidth: 1, borderColor: C.borderStrong, marginTop: 2 },
    radioActive: { borderColor: C.active, backgroundColor: C.active },
    optionBody: { flex: 1, gap: 3 },
    optionTitle: { color: C.textPrimary, fontSize: 13, fontWeight: "600", fontFamily: F.display },
    optionDesc: { color: C.textSecondary, fontSize: 11, fontFamily: F.mono, letterSpacing: 0.2 },
    toggleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 14,
      ...cardBorder,
    },
    toggleBody: { flex: 1, gap: 3 },
    input: {
      backgroundColor: C.bgInput,
      color: C.textPrimary,
      borderRadius: 3,
      paddingHorizontal: 12,
      paddingVertical: 11,
      fontSize: 13,
      borderWidth: 1,
      borderColor: C.border,
      fontFamily: F.mono,
    },
    textarea: { minHeight: 100, textAlignVertical: "top" },
    saveBtn: { backgroundColor: C.active, borderRadius: 3, paddingVertical: 12, alignItems: "center", marginTop: 4 },
    saveBtnText: { color: C.bg, fontSize: 12, fontWeight: "700", letterSpacing: 0.5, fontFamily: F.mono },
    outlineBtn: { ...actionBorder, borderColor: C.active + "80" },
    outlineBtnDisabled: { borderColor: C.border, opacity: 0.5 },
    outlineBtnText: { color: C.active, fontSize: 12, fontWeight: "700", letterSpacing: 0.5, fontFamily: F.mono },
    dangerBtn: { ...actionBorder, borderColor: C.error + "90" },
    dangerBtnDisabled: { opacity: 0.5 },
    dangerBtnText: { color: C.error, fontSize: 12, fontWeight: "700", letterSpacing: 0.5, fontFamily: F.mono },
    sourcesList: { gap: 6 },
    publisherGroup: { gap: 3 },
    sourcesLabel: {
      color: C.textDim,
      fontSize: 9,
      fontWeight: "700",
      letterSpacing: 2,
      fontFamily: F.mono,
      marginTop: 4,
    },
    publisherLabel: {
      color: C.textMuted,
      fontSize: 9,
      fontWeight: "600",
      letterSpacing: 1,
      fontFamily: F.mono,
      marginTop: 2,
    },
    checkRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 8,
      paddingHorizontal: 10,
      ...compactCardBorder,
    },
    checkRowActive: { borderColor: C.active + "50" },
    checkbox: {
      width: 16,
      height: 16,
      ...centerBorder,
      borderColor: C.borderStrong,
    },
    checkboxChecked: { backgroundColor: C.active, borderColor: C.active },
    checkRowLabel: { color: C.textSecondary, fontSize: 12, fontFamily: F.mono },
    checkRowLabelChecked: { color: C.textPrimary },
    fileRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 9,
      ...compactCardBorder,
    },
    fileName: { flex: 1, color: C.textSecondary, fontSize: 12, fontFamily: F.mono },
    fileRemoveBtn: {
      width: 28,
      height: 28,
      ...centerBorder,
      borderColor: C.error + "70",
    },
    fileRemoveBtnDisabled: { opacity: 0.45 },
    __colors: C,
  } as const;
}
